In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier 

In [ ]:
# 1. Number of times pregnant
# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
# 3. Diastolic blood pressure (mm Hg)
# 4. Triceps skin fold thickness (mm)
# 5. 2-Hour serum insulin (mu U/ml)
# 6. Body mass index (weight in kg/(height in m)^2)
# 7. Diabetes pedigree function
# 8. Age (years)
# 9. Class variable (0 or 1)
# load dataset
df = pd.read_csv("dataset.csv")
df

pregnant  glucose  bp  skin-fold  insulin  bmass   diab  age  label
0           6      148  72         35        0   33.6  0.627   50      1
1           1       85  66         29        0   26.6  0.351   31      0
2           8      183  64          0        0   23.3  0.672   32      1
3           1       89  66         23       94   28.1  0.167   21      0
4           0      137  40         35      168   43.1  2.288   33      1
..        ...      ...  ..        ...      ...    ...    ...  ...    ...
763        10      101  76         48      180   32.9  0.171   63      0
764         2      122  70         27        0   36.8  0.340   27      0
765         5      121  72         23      112   26.2  0.245   30      0
766         1      126  60          0        0   30.1  0.349   47      1
767         1       93  70         31        0   30.4  0.315   23      0

[768 rows x 9 columns]

In [ ]:
#split dataset in features and target variable
feature_cols = ['pregnant', 'glucose', 'bp', 'skin-fold', 'insulin', 'bmass', 'diab', 'age']
X = df[feature_cols] # Features
y = df.label # Target variable

In [ ]:
from sklearn.model_selection import train_test_split 
# i.e. 80 % training dataset and 30 % test datasets 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.70) 

In [ ]:
# creating a RF classifier 
clf = RandomForestClassifier(n_estimators = 100)   
  
# Training the model on the training dataset 
# fit function is used to train the model using the training sets as parameters 
clf.fit(X_train, y_train) 
  
# performing predictions on the test dataset 
y_pred = clf.predict(X_test) 
  
# metrics are used to find accuracy or error 
from sklearn import metrics   
  
# using metrics module for accuracy calculation 
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred)) 

ACCURACY OF THE MODEL:  0.7639405204460966


In [ ]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[303,  51],
       [ 76, 108]])

In [ ]:
# predicting if a peron has diabeties  
clf.predict([[1	,85	,66	,29	,0	,26.6	,0.351	,31]]) 

array([0])

In [ ]:
clf.predict([[0	,137	,40	,35	,168	,43.1	,2.288	,33]]) 

array([1])